#!/usr/bin/env node
// Table of contents for every documentation file longer than 100 lines
// (CLAUDE.md → "Docs over 100 lines get a table of contents"). The list of
// its ## and ### headings goes between two marker comments right below the
// file's # title (or below the front matter when there is none) and is only
// ever written by this script:
//
//   node scripts/doc-toc.js           write/refresh every TOC that is due
//   node scripts/doc-toc.js --check   list files whose TOC is missing or stale
//                                     (exit code 1), change nothing
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const MIN_LINES = 100;
const START = "<!-- toc: generated by scripts/doc-toc.js, do not edit by hand -->";
const END = "<!-- /toc -->";
// Not documentation in the sense of the rule: legal text shipped verbatim
// (LICENSE.md is also compared with the page's own copy) and generated notices.
const EXCLUDED = new Set(["LICENSE.md", "desktop/THIRD_PARTY_NOTICES.md"]);
const SKIPPED_DIRS = new Set([".git", "node_modules", "target", "gen", "changelog.d", "worktrees"]);

function listDocs(root = ROOT, dir = "") {
  const out = [];
  for (const ent of fs.readdirSync(path.join(root, dir), { withFileTypes: true })) {
    const rel = dir ? dir + "/" + ent.name : ent.name;
    if (ent.isDirectory()) { if (!SKIPPED_DIRS.has(ent.name)) out.push(...listDocs(root, rel)); }
    else if (ent.name.endsWith(".md") && !EXCLUDED.has(rel)) out.push(rel);
  }
  return out.sort();
}

// The text without an existing TOC block (and the blank line after it).
function stripToc(text) {
  const a = text.indexOf(START);
  if (a === -1) return text;
  const b = text.indexOf(END, a);
  if (b === -1) return text;
  return text.slice(0, a) + text.slice(b + END.length).replace(/^\n\n?/, "");
}

// GitHub's heading anchors: lowercase, drop everything but letters, digits,
// spaces, "_" and "-", spaces become "-", repeats get "-1", "-2", ...
function slugger() {
  const seen = new Map();
  return text => {
    const base = text.toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu, "").trim().replace(/\s/g, "-");
    const n = seen.get(base) || 0;
    seen.set(base, n + 1);
    return n ? base + "-" + n : base;
  };
}

// ## and ### headings outside fenced code blocks, with their anchors.
function headings(text) {
  const slug = slugger();
  const out = [];
  let fence = null;
  for (const line of text.split("\n")) {
    const f = /^\s*(```|~~~)/.exec(line);
    if (f) { fence = fence === null ? f[1] : (fence === f[1] ? null : fence); continue; }
    if (fence !== null) continue;
    const h = /^(#{1,6})\s+(.*?)\s*#*\s*$/.exec(line);
    if (!h) continue;
    const label = h[2].replace(/`/g, "");
    const anchor = slug(label);
    if (h[1].length === 2 || h[1].length === 3) out.push({ level: h[1].length, label, anchor });
  }
  return out;
}

function tocBlock(text) {
  const hs = headings(text);
  if (hs.length < 2) return null; // nothing to navigate
  const lines = hs.map(h => (h.level === 3 ? "  " : "") + "- [" + h.label.replace(/[[\]]/g, "\\$&") + "](#" + h.anchor + ")");
  return START + "\n" + lines.join("\n") + "\n" + END;
}

// The file's content with an up-to-date TOC (or without one when it is
// short or has fewer than two headings).
function withToc(text) {
  const bare = stripToc(text);
  if (bare.split("\n").length <= MIN_LINES) return bare;
  const block = tocBlock(bare);
  if (!block) return bare;
  const lines = bare.split("\n");
  let at = 0;
  if (lines[0] === "---") { const end = lines.indexOf("---", 1); if (end !== -1) at = end + 1; }
  const title = lines.findIndex((l, i) => i >= at && /^#\s/.test(l));
  if (title !== -1 && lines.slice(at, title).every(l => !l.trim())) at = title + 1;
  while (at < lines.length && !lines[at].trim()) at++;
  lines.splice(at, 0, block, "");
  if (at > 0 && lines[at - 1].trim()) lines.splice(at, 0, "");
  return lines.join("\n");
}

function run(root = ROOT, { check = false } = {}) {
  const stale = [];
  for (const rel of listDocs(root)) {
    const file = path.join(root, rel);
    const text = fs.readFileSync(file, "utf8");
    const want = withToc(text);
    if (want === text) continue;
    stale.push(rel);
    if (!check) fs.writeFileSync(file, want);
  }
  return stale;
}

function main(argv) {
  const check = argv.includes("--check");
  const stale = run(ROOT, { check });
  if (check && stale.length) {
    console.log("TOC missing or stale (run `node scripts/doc-toc.js`):\n  " + stale.join("\n  "));
    process.exitCode = 1;
  } else if (!check) {
    console.log(stale.length ? "updated:\n  " + stale.join("\n  ") : "all TOCs up to date");
  }
}

if (require.main === module) main(process.argv.slice(2));

module.exports = { listDocs, headings, withToc, stripToc, run, START, END, MIN_LINES };
